### ISSUE TITLE
Modificación readme

### ISSUE THREAD

**Issue by ghost** [Carolinadelb/scl-2018-05-bc-core-am-datadashboard#1]
Hola, Carolina:

Realice algunas modificaciones en el readme y el style.css. Por favor, sincroniza mi repositorio.

Saludos,
Loreto Gutiérrez H.

**Comment by Carolinadelb** [comment]
Hola Loreto,

Muchas gracias por avisarme de estos cambios. Haré la sincronización inmediatamente. 

Saludos,
Carolina Delgado B.
