### ISSUE TITLE
Cambios a botones

### ISSUE THREAD

**Issue by ghost** [Carolinadelb/scl-2018-05-bc-core-am-datadashboard#2]
Hola, Carolina:

Agregué los enlaces de los archivos .html correspondientes a cada uno de los botones.

Que tengas un buen día.
Saludos,
Loreto Gutiérrez H.

**Comment by Carolinadelb** [comment]
Muchas Gracias Loreto Camila, más conocida como Bambi y bambicita para las amigas. 
Hare la sincronización inmediatamente.
Que tengas un termino de día espectacular.

Saludos, Carolina
